env.active=online
app.name=intransit-schedule
server.port=32003

feign.client.timeout.read=10000
feign.client.timeout.connect=10000

nacos.address=10.132.75.106:8848,10.132.75.107:8848,10.132.75.108:8848
nacos.namespace=fe5faa1d-0957-4cfa-96a8-ea6da6d67f12
nacos.username=nacos
nacos.password=nacos
