env.active=test
app.name=intransit-schedule
server.port=9021

feign.client.timeout.read=10000
feign.client.timeout.connect=10000

nacos.address=10.132.85.31:8848
nacos.namespace=360c8c88-30ee-4abb-bb37-d1a84828e235
nacos.username=nacos
nacos.password=nacos

