env.active=uat
app.name=intransit-schedule
server.port=9021


feign.client.timeout.read=10000
feign.client.timeout.connect=10000

nacos.address=10.132.85.31:8848
nacos.namespace=622f4afd-0cae-417d-a316-0a9455c12a07
nacos.username=nacos
nacos.password=nacos
nacos.discovery.enabled=true